insert into public.articles (
  slug,
  status,
  publish_at,
  title_en,
  title_zh,
  excerpt_en,
  excerpt_zh,
  body_en,
  body_zh,
  category_en,
  category_zh,
  author,
  team,
  source_name,
  source_url,
  cover_url,
  images,
  xhs_title,
  xhs_content,
  hashtags
)
values (
  'airforce-animatronics-single-tube',
  'published',
  now(),
  'AirForce — Animatronics Structures from a Single Tube',
  '一根管子撑起人类重量？AirForce 气动装置',
  'A fabrication system that turns one continuous inflatable tube into large-scale, load-bearing animated structures.',
  'AirForce 用一根连续充气管构建大型承重动态结构，让“结构本身”同时成为“驱动力”。',
  '[
    "Created by a team of researchers at the Hasso Plattner Institute, AirForce replaces both the static elements and the pneumatic actuators of a conventional animatronic structure with a single tube-based system.",
    "At the center of the project is a Blender plug-in for designing and animating tube-based trusses.",
    "The team increased the tube cross-section, changed the sealing system, and developed custom blowers so the structures could lift human weight.",
    "AirForce can be assembled on the ground, transported while deflated, unfolded on site, and later refolded with almost complete material reuse."
  ]'::jsonb,
  '[
    "来自哈索·普拉特纳研究所的研究团队开发了 AirForce，以连续管材同时承担静态结构和气动驱动功能。",
    "系统核心是一款 Blender 插件，它会实时规划单管在桁架结构中的路径，并把指定结构段转化为执行器。",
    "团队增大管材横截面、改进密封方式并使用定制鼓风机，使结构足以抬起人体重量。",
    "结构可在地面组装，以放气状态运输和部署，也可重新折叠，材料复用率接近百分之百。"
  ]'::jsonb,
  'Art & Technology / Digital Fabrication',
  '艺术科技 / 数字制造',
  'Filip',
  'Lukas Rambold, Robert Kovacs, Min Deng, Antonius Naumann, Konrad Gerlach, Horatio Hamkins, Helena Lendowski, Chiao Fang, Shohei Katakura, Conrad Lempert, Muhammad Abdullah, Patrick Baudisch',
  'CreativeApplications.Net',
  'https://www.creativeapplications.net/project/airforce-animatronics-structures-from-a-single-tube/',
  '/images/articles/airforce/00-cover.jpg',
  array[
    '/images/articles/airforce/01.jpg',
    '/images/articles/airforce/02.jpg',
    '/images/articles/airforce/03.jpg',
    '/images/articles/airforce/04.jpg',
    '/images/articles/airforce/05.jpg',
    '/images/articles/airforce/06.jpg',
    '/images/articles/airforce/07.jpg',
    '/images/articles/airforce/08.png'
  ],
  '一根管子撑起人类重量？气动装置新物种',
  '',
  array['#ArtBOP', '#BOPHAUS', '#艺术科技', '#数字制造', '#交互设计']
)
on conflict (slug) do update set
  status = excluded.status,
  publish_at = excluded.publish_at,
  title_en = excluded.title_en,
  title_zh = excluded.title_zh,
  excerpt_en = excluded.excerpt_en,
  excerpt_zh = excluded.excerpt_zh,
  body_en = excluded.body_en,
  body_zh = excluded.body_zh,
  category_en = excluded.category_en,
  category_zh = excluded.category_zh,
  author = excluded.author,
  team = excluded.team,
  source_name = excluded.source_name,
  source_url = excluded.source_url,
  cover_url = excluded.cover_url,
  images = excluded.images,
  hashtags = excluded.hashtags;
